package com.forgesense.common.domain;

/**
 * Canonical operational event types.
 */
public enum EventType {
    TELEMETRY_RECEIVED,
    TELEMETRY_NORMALIZED,
    MACHINE_STATE_CHANGED,
    ANOMALY_DETECTED,
    PREDICTION_UPDATED,
    FAILURE_RISK_CHANGED,
    ALERT_CREATED,
    ALERT_ACKNOWLEDGED,
    ALERT_INVESTIGATING,
    ALERT_RESOLVED,
    MAINTENANCE_CREATED,
    MAINTENANCE_STARTED,
    MAINTENANCE_COMPLETED,
    SIMULATION_STARTED,
    SIMULATION_COMPLETED,
    MACHINE_OFFLINE,
    MACHINE_RECOVERED
}