/**
 * Data basis — the honesty vocabulary of the control room.
 *
 * Every meaningful number in ForgeSense carries one of these classifications.
 * The UI must never present a synthetic value as an observed measurement, a
 * model estimate as a guarantee, or a simulated impact as a realised loss.
 *
 * This module is the single place that decides those words, so the vocabulary
 * cannot drift between views.
 */

export const DATA_BASIS = {
  /** A value read directly from a system of record. */
  OBSERVED: 'OBSERVED',
  /** Computed by the platform from observed values (counts, averages). */
  DERIVED: 'DERIVED',
  /** Produced by the ML service. */
  PREDICTED: 'PREDICTED',
  /** Produced by the synthetic simulator. */
  SYNTHETIC: 'SYNTHETIC',
  /** Produced by the what-if simulation engine. */
  SIMULATED: 'SIMULATED',
  /** No trustworthy value exists right now. */
  UNAVAILABLE: 'UNAVAILABLE',
} as const;

export type DataBasis = (typeof DATA_BASIS)[keyof typeof DATA_BASIS];

export interface BasisDescriptor {
  basis: DataBasis;
  label: string;
  /** One-line explanation rendered in tooltips and provenance panels. */
  meaning: string;
  cssVar: string;
}

const DESCRIPTORS: Record<DataBasis, BasisDescriptor> = {
  OBSERVED: {
    basis: DATA_BASIS.OBSERVED,
    label: 'Observed',
    meaning: 'Read directly from a system of record. In this deployment the underlying feed is synthetic.',
    cssVar: 'var(--basis-observed)',
  },
  DERIVED: {
    basis: DATA_BASIS.DERIVED,
    label: 'Derived',
    meaning: 'Computed by the platform from observed values — for example a fleet average.',
    cssVar: 'var(--basis-derived)',
  },
  PREDICTED: {
    basis: DATA_BASIS.PREDICTED,
    label: 'Model predicted',
    meaning: 'Estimated by the ML service. Not a measurement and not a guarantee.',
    cssVar: 'var(--basis-predicted)',
  },
  SYNTHETIC: {
    basis: DATA_BASIS.SYNTHETIC,
    label: 'Synthetic',
    meaning: 'Generated by the telemetry simulator. Represents no real machine.',
    cssVar: 'var(--basis-synthetic)',
  },
  SIMULATED: {
    basis: DATA_BASIS.SIMULATED,
    label: 'Simulated',
    meaning: 'Produced by the what-if engine under a modelled assumption. Not an observed outcome.',
    cssVar: 'var(--basis-simulated)',
  },
  UNAVAILABLE: {
    basis: DATA_BASIS.UNAVAILABLE,
    label: 'Unavailable',
    meaning: 'No trustworthy value is available right now.',
    cssVar: 'var(--basis-unavailable)',
  },
};

export function describeBasis(basis: DataBasis): BasisDescriptor {
  return DESCRIPTORS[basis];
}

/**
 * Map the backend's free-form `dataBasis` strings onto the controlled
 * vocabulary. The backend emits SYNTHETIC / OBSERVED / ESTIMATED; ESTIMATED
 * is a derived modelling output, so it maps to DERIVED.
 */
export function resolveBasis(raw: string | string[] | undefined | null): DataBasis {
  const values = Array.isArray(raw) ? raw : raw ? [raw] : [];
  const upper = values.map((v) => String(v).toUpperCase());

  if (upper.includes('SYNTHETIC')) return DATA_BASIS.SYNTHETIC;
  if (upper.includes('SIMULATED')) return DATA_BASIS.SIMULATED;
  if (upper.includes('PREDICTED')) return DATA_BASIS.PREDICTED;
  if (upper.includes('OBSERVED')) return DATA_BASIS.OBSERVED;
  if (upper.includes('ESTIMATED')) return DATA_BASIS.DERIVED;
  if (upper.includes('DERIVED')) return DATA_BASIS.DERIVED;
  return DATA_BASIS.UNAVAILABLE;
}

/**
 * The strongest (most specific) basis across a set, used when a panel mixes
 * several sources. Specificity order: unavailable < observed < derived <
 * synthetic < simulated < predicted.
 */
const PRECEDENCE: DataBasis[] = [
  DATA_BASIS.UNAVAILABLE,
  DATA_BASIS.OBSERVED,
  DATA_BASIS.DERIVED,
  DATA_BASIS.SYNTHETIC,
  DATA_BASIS.SIMULATED,
  DATA_BASIS.PREDICTED,
];

export function strongestBasis(bases: DataBasis[]): DataBasis {
  let best: DataBasis = DATA_BASIS.UNAVAILABLE;
  for (const basis of bases) {
    if (PRECEDENCE.indexOf(basis) > PRECEDENCE.indexOf(best)) best = basis;
  }
  return best;
}
